[patch.crates-io]
sha2 = { branch = "sha2ni", git = "https://github.com/Zondax/hashes", package = "sha2ni" }

[workspace]
members = [
    "service",
    "signer",
    "signer-ffi",
    "signer-wasm"
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
