# filecoin-service - Example configuration file# https://documenter.getpostman.com/view/4872192/SWLh5mUd?version=latest

[remote_node]
url = "http://86.192.13.13:1234/rpc/v0"
jwt = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.xK1G26jlYnAEnGLJzN1RLywghc4p4cHI6ax_6YOv0aI"

[service]
address = "127.0.0.1:3030"
