[package]
name = "filecoin-signer"
version = "0.1.0"
authors = ["Zondax <info@zondax.ch>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/Zondax/filecoin-signing-tools"
description =""

[dependencies]
thiserror = "1.0"
base64 = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.11.1"
rayon = "1"

bls-signatures = "0.6.1"

# Crypto related
hex = { git = "https://github.com/Zondax/rust-hex", rev="6e35fb48999278c8c6c75b099baa4ea2a9d1d12b" }
getrandom="0.1.14"
libsecp256k1 = "0.3.5"
blake2b_simd = "0.5.10"
hmac = "0.8.1"
zeroize = { version = "1.1", default-features = false, features = ["zeroize_derive"] }
sha2 = "0.9.1"

# logging
log = "0.4"
env_logger = "0.7"

arbitrary = { optional = true, features = ["derive"], version = "0.4" }
ffi-support = { optional = true, version = "0.4" }

# TODO: Update once crates are available
forest_vm = "0.2.0"
forest_message = "0.3.0"
forest_address = "0.2.0"
forest_encoding = "0.1.1"
forest_cid = "0.1.0"

# TODO: Maybe we can replace these with something leaner
tiny-bip39 = "0.7.3"
num_bigint_chainsafe = { package = "forest_bigint", version = "0.1.0"}

zx-bip44 = "0.1.0"

extras = { path = "../extras"}

[dev-dependencies]
rand_chacha = "0.2.2"
rand = "0.7"

[features]
default = []
with-arbitrary = ["arbitrary"]
with-ffi-support = ["ffi-support"]
